"""
Teaching Context Model.

Generated by the Teaching Engine.

Reference: 05_DATA_AND_MODEL_DESIGN/01_DATABASE_SCHEMA.md (Section 5 - Teaching Context)
Reference: 05_DATA_AND_MODEL_DESIGN/02_ENTITY_RELATIONSHIP_MODEL.md (Section 12 - Foreign Keys)
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.database.base import Base, utcnow

if TYPE_CHECKING:
    from backend.models.ai_interaction import AIInteraction
    from backend.models.student_profile import StudentProfile
    from backend.models.topic import Topic


class TeachingContext(Base):
    """
    Teaching strategy generated for a student on a topic, consumed by
    the AI Service Layer to produce instructional content.

    Cascade policy: generated/derivative adaptive data — deleting the
    owning StudentProfile cascades here. The `topic_id` foreign key
    uses RESTRICT. Its own children (AIInteraction) are educational
    records and use RESTRICT in turn, so a TeachingContext with AI
    interaction history cannot be silently deleted.
    """

    __tablename__ = "teaching_contexts"

    context_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    student_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("student_profiles.student_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    topic_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("topics.topic_id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    teaching_strategy: Mapped[str] = mapped_column(String, nullable=False)
    learning_objective: Mapped[str] = mapped_column(Text, nullable=False)
    difficulty: Mapped[str] = mapped_column(String, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow
    )

    student: Mapped["StudentProfile"] = relationship(back_populates="teaching_contexts")
    topic: Mapped["Topic"] = relationship(passive_deletes="all")

    ai_interactions: Mapped[list["AIInteraction"]] = relationship(
        back_populates="context",
        passive_deletes="all",
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return (
            f"TeachingContext(context_id={self.context_id!r}, "
            f"teaching_strategy={self.teaching_strategy!r})"
        )
