"""
Recommendation Model.

Reference: 05_DATA_AND_MODEL_DESIGN/01_DATABASE_SCHEMA.md (Section 5 - Recommendation)
Reference: 05_DATA_AND_MODEL_DESIGN/02_ENTITY_RELATIONSHIP_MODEL.md (Section 12 - Foreign Keys)
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Integer, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.database.base import Base, utcnow

if TYPE_CHECKING:
    from backend.models.student_profile import StudentProfile
    from backend.models.topic import Topic


class Recommendation(Base):
    """
    A personalized recommendation generated by the Recommendation
    Engine for a student on a topic.

    Cascade policy: this is generated/derivative adaptive data (not raw
    evidence), so deleting the owning StudentProfile cascades here. The
    `topic_id` foreign key uses RESTRICT — a Topic cannot be deleted
    while recommendations still reference it.
    """

    __tablename__ = "recommendations"

    recommendation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    student_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("student_profiles.student_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    topic_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("topics.topic_id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    recommendation_type: Mapped[str] = mapped_column(String, nullable=False)
    priority: Mapped[int] = mapped_column(Integer, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow
    )

    student: Mapped["StudentProfile"] = relationship(back_populates="recommendations")
    topic: Mapped["Topic"] = relationship(passive_deletes="all")

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return f"Recommendation(recommendation_id={self.recommendation_id!r}, priority={self.priority!r})"
