"""
Context Builder (documented as "Context Manager").

Builds the learner context required by the AI Service Layer.

Educational Intelligence and Teaching Intelligence provide the
educational decisions. This module only gathers learner data and
combines it with the Teaching Context generated by Module 10.

Reference: 02_System_Architecture/04_AI_Architecture.md
(Section 10 - Context Manager)

Reference: 05_DATA_AND_MODEL_DESIGN/05_AI_PROMPT_MODEL.md
(Section 8 - Learner Context)
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass

from sqlalchemy.orm import Session

from backend.algorithms.irt.estimator import AbilityCategory, classify_ability
from backend.algorithms.mastery_engine import (
    MasteryLevel,
    classify_mastery_level,
    is_strong_topic,
    is_weak_topic,
)
from backend.algorithms.teaching_engine.teaching_engine import TeachingContextData
from backend.config import settings
from backend.core.exceptions import (
    AuthorizationError,
    NotFoundError,
    ValidationFailedError,
)
from backend.models import (
    StudentProfile,
    TeachingContext,
    Topic,
    User,
    UserRole,
)
from backend.repositories import (
    LearnerProfileRepository,
    TeachingContextRepository,
    TopicMasteryRepository,
    TopicRepository,
)

#: Caps weak/strong topic lists so prompts stay small.
_MAX_CONTEXT_TOPICS = 5

#: Caps how much of a stored AI response is echoed back
#: into a new prompt as previous-interaction context.
_INTERACTION_SUMMARY_CHARS = 160


@dataclass(frozen=True)
class LearnerContext:
    """
    Structured educational context for one AI request.

    The Teaching Context is generated by Teaching Intelligence and
    supplied to this object rather than being reconstructed here.
    """

    student_id: uuid.UUID
    topic_id: uuid.UUID
    topic_title: str

    ability_theta: float
    ability_category: AbilityCategory

    topic_mastery: float | None
    mastery_level: MasteryLevel

    weak_topic_titles: list[str]
    strong_topic_titles: list[str]

    learning_objective: str | None
    recent_interactions: list[str]

    teaching_context: TeachingContextData


class ContextBuilder:
    """
    Assembles a LearnerContext for one student and topic.

    This module gathers learner evidence and combines it with the
    Teaching Context generated by the Teaching Engine.

    It does not make new pedagogical decisions.
    """

    def __init__(self, db: Session) -> None:
        self.db = db

        self.learner_profiles = LearnerProfileRepository(db)
        self.topic_masteries = TopicMasteryRepository(db)
        self.topics = TopicRepository(db)
        self.teaching_contexts = TeachingContextRepository(db)

    def build(
        self,
        *,
        actor: User,
        topic_id: uuid.UUID,
        teaching_context: TeachingContextData,
    ) -> LearnerContext:
        """
        Build the complete learner context for an AI request.

        `teaching_context` is produced by Teaching Intelligence and
        contains the pedagogical decision for the current learning state.
        """

        student = self._require_student(actor)
        topic = self._require_topic(topic_id)

        # ---------------------------------------------------------
        # Learner profile / IRT ability
        # ---------------------------------------------------------

        profile_page = self.learner_profiles.find_all(
            student_id=student.student_id,
            limit=1,
        )

        if profile_page.total == 0:
            raise NotFoundError(
                "No learner data yet — attempt an assessment first."
            )

        profile = profile_page.items[0]

        ability_category = classify_ability(
            profile.ability_theta
        )

        # ---------------------------------------------------------
        # Topic mastery / BKT
        # ---------------------------------------------------------

        masteries = self.topic_masteries.find_all(
            learner_profile_id=profile.learner_profile_id,
            limit=10_000,
        )

        topic_mastery = next(
            (
                mastery.mastery_score
                for mastery in masteries.items
                if mastery.topic_id == topic_id
            ),
            None,
        )

        mastery_level = classify_mastery_level(
            topic_mastery
        )

        # ---------------------------------------------------------
        # Weak / strong topics
        # ---------------------------------------------------------

        weak_titles, strong_titles = (
            self._weak_and_strong_topic_titles(
                masteries.items
            )
        )

        # ---------------------------------------------------------
        # Previous AI interactions
        # ---------------------------------------------------------

        recent_interactions = self._recent_interactions(
            student_id=student.student_id,
            topic_id=topic_id,
        )

        # ---------------------------------------------------------
        # Final learner context
        # ---------------------------------------------------------

        return LearnerContext(
            student_id=student.student_id,
            topic_id=topic_id,
            topic_title=topic.title,
            ability_theta=profile.ability_theta,
            ability_category=ability_category,
            topic_mastery=topic_mastery,
            mastery_level=mastery_level,
            weak_topic_titles=weak_titles,
            strong_topic_titles=strong_titles,
            learning_objective=teaching_context.learning_objective,
            recent_interactions=recent_interactions,
            teaching_context=teaching_context,
        )

    def _weak_and_strong_topic_titles(
        self,
        masteries: list,
    ) -> tuple[list[str], list[str]]:
        """
        Return capped lists of weak and strong topic titles.
        """

        weak_titles: list[str] = []
        strong_titles: list[str] = []

        for mastery in masteries:

            if (
                is_weak_topic(mastery.mastery_score)
                and len(weak_titles) < _MAX_CONTEXT_TOPICS
            ):
                topic = self.topics.find_by_id(
                    mastery.topic_id
                )

                if topic is not None:
                    weak_titles.append(topic.title)

            elif (
                is_strong_topic(mastery.mastery_score)
                and len(strong_titles) < _MAX_CONTEXT_TOPICS
            ):
                topic = self.topics.find_by_id(
                    mastery.topic_id
                )

                if topic is not None:
                    strong_titles.append(topic.title)

        return weak_titles, strong_titles

    def _recent_interactions(
        self,
        *,
        student_id: uuid.UUID,
        topic_id: uuid.UUID,
    ) -> list[str]:
        """
        Retrieve recent AI interactions for this student and topic.
        """

        context_page = self.teaching_contexts.find_all(
            student_id=student_id,
            topic_id=topic_id,
            limit=settings.AI_RECENT_INTERACTIONS_LIMIT,
            order_by=TeachingContext.generated_at,
            descending=True,
        )

        summaries: list[str] = []

        for context in context_page.items:

            for interaction in context.ai_interactions:

                snippet = (
                    interaction.response[
                        :_INTERACTION_SUMMARY_CHARS
                    ]
                    .strip()
                )

                summaries.append(
                    f"{context.teaching_strategy}: {snippet}"
                )

        return summaries[
            : settings.AI_RECENT_INTERACTIONS_LIMIT
        ]

    def _require_student(
        self,
        actor: User,
    ) -> StudentProfile:
        """
        Ensure the requesting user is a student with a profile.
        """

        if actor.role != UserRole.STUDENT:
            raise AuthorizationError(
                "Only students receive AI tutoring."
            )

        if actor.student_profile is None:
            raise ValidationFailedError(
                "A student profile must be created "
                "(PATCH /users/{id}) before requesting AI tutoring."
            )

        return actor.student_profile

    def _require_topic(
        self,
        topic_id: uuid.UUID,
    ) -> Topic:
        """
        Ensure the requested topic exists.
        """

        topic = self.topics.find_by_id(topic_id)

        if topic is None:
            raise NotFoundError(
                "Topic not found."
            )

        return topic