"""
Teaching Content — Structured AI Response Schema.

Defines the structured instructional content produced by the AI
Teaching Content Engine. Each field is optional at the dataclass
level; the response validator enforces which fields are required
for each TeachingStrategy.

The TeachingContent dataclass is the final output of the AI
Teaching Content pipeline:

    TeachingContextData → Prompt → AI Provider → Raw Text
        → parse_teaching_content() → TeachingContent
        → validate_teaching_content() → Application

Teaching strategy, difficulty, topic, and learning objective are
passthrough values from TeachingContextData — the LLM does not
decide these. Only the instructional text fields (explanation,
examples, practice_question, etc.) are generated by the LLM.

Reference: 02_System_Architecture/04_AI_Architecture.md
(Section 17 - AI Output Types)
"""

from __future__ import annotations

from dataclasses import dataclass, field

from backend.algorithms.teaching_engine.teaching_strategy_engine import (
    TeachingStrategy,
)


@dataclass(frozen=True)
class TeachingContent:
    """
    Structured AI-generated instructional content.

    Passthrough fields (from TeachingContextData — never LLM-decided):
        teaching_strategy, topic, learning_objective, difficulty

    Generated fields (produced by the LLM within the constraints
    set by Teaching Intelligence):
        explanation, examples, key_takeaways, practice_question,
        hints, expected_answer, follow_up_activity
    """

    # -- Passthrough fields (authoritative source: TeachingContextData) --

    teaching_strategy: str
    topic: str
    learning_objective: str | None
    difficulty: str

    # -- Generated content fields --

    explanation: str | None = None
    examples: tuple[str, ...] = field(default_factory=tuple)
    key_takeaways: tuple[str, ...] = field(default_factory=tuple)
    practice_question: str | None = None
    hints: tuple[str, ...] = field(default_factory=tuple)
    expected_answer: str | None = None
    follow_up_activity: str | None = None


# -- Strategy → Required Fields Mapping --

#: For each TeachingStrategy, the set of content field names that
#: must be non-empty in a valid TeachingContent response.
REQUIRED_FIELDS_BY_STRATEGY: dict[str, set[str]] = {
    TeachingStrategy.CONCEPT_INTRODUCTION.value: {
        "explanation",
        "examples",
        "key_takeaways",
    },
    TeachingStrategy.GUIDED_REVISION.value: {
        "explanation",
        "examples",
    },
    TeachingStrategy.GUIDED_PRACTICE.value: {
        "practice_question",
        "hints",
        "expected_answer",
    },
    TeachingStrategy.ASSESSMENT.value: {
        "practice_question",
        "expected_answer",
    },
    TeachingStrategy.PERSONALIZED_EXPLANATION.value: {
        "explanation",
        "examples",
    },
    TeachingStrategy.PROGRESSION.value: {
        "explanation",
        "key_takeaways",
    },
}
