"""initial schema

Revision ID: d01290c1ebe2
Revises: 
Create Date: 2026-07-26 13:44:11.621637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01290c1ebe2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('Student', 'Teacher', 'Admin', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('modules',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_index(op.f('ix_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_number', sa.String(), nullable=False),
    sa.Column('program', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('teacher_profiles',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_index(op.f('ix_teacher_profiles_user_id'), 'teacher_profiles', ['user_id'], unique=True)
    op.create_table('learner_profiles',
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('ability_theta', sa.Float(), nullable=False),
    sa.Column('overall_mastery', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_profile_id')
    )
    op.create_index(op.f('ix_learner_profiles_ability_theta'), 'learner_profiles', ['ability_theta'], unique=False)
    op.create_index(op.f('ix_learner_profiles_student_id'), 'learner_profiles', ['student_id'], unique=True)
    op.create_table('topics',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index(op.f('ix_topics_module_id'), 'topics', ['module_id'], unique=False)
    op.create_table('assessments',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('assessment_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_assessments_created_at'), 'assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_assessments_topic_id'), 'assessments', ['topic_id'], unique=False)
    op.create_table('learning_objectives',
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('objective_id')
    )
    op.create_index(op.f('ix_learning_objectives_topic_id'), 'learning_objectives', ['topic_id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('path_id')
    )
    op.create_index(op.f('ix_learning_paths_student_id'), 'learning_paths', ['student_id'], unique=False)
    op.create_index(op.f('ix_learning_paths_topic_id'), 'learning_paths', ['topic_id'], unique=False)
    op.create_table('progress_history',
    sa.Column('progress_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_index(op.f('ix_progress_history_mastery_score'), 'progress_history', ['mastery_score'], unique=False)
    op.create_index(op.f('ix_progress_history_student_id'), 'progress_history', ['student_id'], unique=False)
    op.create_index(op.f('ix_progress_history_topic_id'), 'progress_history', ['topic_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    op.create_index(op.f('ix_recommendations_topic_id'), 'recommendations', ['topic_id'], unique=False)
    op.create_table('teaching_contexts',
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('teaching_strategy', sa.String(), nullable=False),
    sa.Column('learning_objective', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('context_id')
    )
    op.create_index(op.f('ix_teaching_contexts_student_id'), 'teaching_contexts', ['student_id'], unique=False)
    op.create_index(op.f('ix_teaching_contexts_topic_id'), 'teaching_contexts', ['topic_id'], unique=False)
    op.create_table('topic_masteries',
    sa.Column('mastery_id', sa.UUID(), nullable=False),
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.learner_profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('mastery_id')
    )
    op.create_index(op.f('ix_topic_masteries_learner_profile_id'), 'topic_masteries', ['learner_profile_id'], unique=False)
    op.create_index(op.f('ix_topic_masteries_mastery_score'), 'topic_masteries', ['mastery_score'], unique=False)
    op.create_index(op.f('ix_topic_masteries_topic_id'), 'topic_masteries', ['topic_id'], unique=False)
    op.create_table('ai_interactions',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('ai_provider', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['teaching_contexts.context_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_index(op.f('ix_ai_interactions_context_id'), 'ai_interactions', ['context_id'], unique=False)
    op.create_index(op.f('ix_ai_interactions_created_at'), 'ai_interactions', ['created_at'], unique=False)
    op.create_table('assessment_items',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('bloom_level', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_assessment_items_assessment_id'), 'assessment_items', ['assessment_id'], unique=False)
    op.create_table('assessment_responses',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('selected_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['assessment_items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index(op.f('ix_assessment_responses_item_id'), 'assessment_responses', ['item_id'], unique=False)
    op.create_index(op.f('ix_assessment_responses_student_id'), 'assessment_responses', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_responses_student_id'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_item_id'), table_name='assessment_responses')
    op.drop_table('assessment_responses')
    op.drop_index(op.f('ix_assessment_items_assessment_id'), table_name='assessment_items')
    op.drop_table('assessment_items')
    op.drop_index(op.f('ix_ai_interactions_created_at'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_context_id'), table_name='ai_interactions')
    op.drop_table('ai_interactions')
    op.drop_index(op.f('ix_topic_masteries_topic_id'), table_name='topic_masteries')
    op.drop_index(op.f('ix_topic_masteries_mastery_score'), table_name='topic_masteries')
    op.drop_index(op.f('ix_topic_masteries_learner_profile_id'), table_name='topic_masteries')
    op.drop_table('topic_masteries')
    op.drop_index(op.f('ix_teaching_contexts_topic_id'), table_name='teaching_contexts')
    op.drop_index(op.f('ix_teaching_contexts_student_id'), table_name='teaching_contexts')
    op.drop_table('teaching_contexts')
    op.drop_index(op.f('ix_recommendations_topic_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_progress_history_topic_id'), table_name='progress_history')
    op.drop_index(op.f('ix_progress_history_student_id'), table_name='progress_history')
    op.drop_index(op.f('ix_progress_history_mastery_score'), table_name='progress_history')
    op.drop_table('progress_history')
    op.drop_index(op.f('ix_learning_paths_topic_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_student_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_learning_objectives_topic_id'), table_name='learning_objectives')
    op.drop_table('learning_objectives')
    op.drop_index(op.f('ix_assessments_topic_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_created_at'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_topics_module_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_learner_profiles_student_id'), table_name='learner_profiles')
    op.drop_index(op.f('ix_learner_profiles_ability_theta'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_index(op.f('ix_teacher_profiles_user_id'), table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_modules_course_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('courses')
    sa.Enum('Student', 'Teacher', 'Admin', name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
